UCRYPTO_MOD_DIR := $(USERMOD_DIR)

SRC_USERMOD += $(UCRYPTO_MOD_DIR)/moducrypto.c

CFLAGS_USERMOD += -I$(UCRYPTO_MOD_DIR)

CFLAGS_USERMOD += -DMICROPY_PY_UCRYPTO=1
CFLAGS_USERMOD += -DMICROPY_PY_UCRYPTO_NUMBER=1
CFLAGS_USERMOD += -DMICROPY_PY_UCRYPTO_PUBLIC_KEY=1
