UCRYPTO_MOD_DIR := $(USERMOD_DIR)

SRC_USERMOD += $(UCRYPTO_MOD_DIR)/moducrypto.c
SRC_USERMOD += $(UCRYPTO_MOD_DIR)/tomsfastmath/tfm_mpi.c

CFLAGS_USERMOD += -I$(UCRYPTO_MOD_DIR)

CFLAGS_USERMOD += -DMICROPY_PY_UCRYPTO=1
